
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import SessionProvider from "@/hocs/session-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../app/api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Wrapper from '../components/wrapper'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface session {
  accessToken?: string;
  id?: number;
  user_name?: string;
  permission?: boolean;
  authority_cards?: string;
  expires?: string;
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = (await getServerSession(authOptions)) as session;
  const token = session?.accessToken;
  // console.log(token)
  // if (token) {
  //   console.log("makjbka");
  //   redirect("/login");
  // }
  return (
    <html lang="en">
      <body className={"m-10"}>
        <SessionProvider>
        <Wrapper>
        {children}
        </Wrapper>
          </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
